### ISSUE TITLE
[FEATURE REQUEST] Half-credit filter

### ISSUE THREAD

**Issue by tlarkworthy** [benb116/PennCourseSearch#48]
It would be great if people could filter searches by course credit (i.e. toggle showing only courses that are 0.5CU for a particular search term)! It's hard to know what half-credit courses are offered since PennInTouch doesn't have this feature.

**Comment by benb116** [comment]
Great idea, shouldn't be too difficult to implement

**Comment by benb116** [comment]
Added, let me know if you find any issues with the credit filter!
