### ISSUE TITLE
Engineering Requirements

### ISSUE THREAD

**Issue by dylanmann** [benb116/PennCourseSearch#49]
Have you thought about adding a filter for engineering requirements (Math/Nat Sci/Tech/SS/H courses)?  Is that sort of information stored with the courses in the same place as the wharton/college requirements?

In the worst case, I figure it's possible to get close with just filtering by course department and adding some custom exceptions from the penn engineering requirement pages [here](https://www.seas.upenn.edu/undergraduate/handbook/courses/math-courses.php), [here](https://www.seas.upenn.edu/undergraduate/handbook/courses/nat-science-courses.php), [here](https://www.seas.upenn.edu/undergraduate/handbook/courses/ssh-breadth.php), etc

**Comment by benb116** [comment]
Yeah I've looked into doing this. Unfortunately, the info for SEAS requirements is not included in the main Penn InTouch API, so I'd have to manually add this the way you said. But it would be a nice addition for SEAS students and probably not too difficult, so I'll keep this on the radar.

**Comment by benb116** [comment]
Added!

**Comment by dylanmann** [comment]
Hurray! Thanks Ben!
